// note 编辑数学：转发到框架 text-edit，保持旧 import 路径。

export {
  layoutDoc,
  caretLine,
  caretX,
  caretFromX,
  insertAt,
  backspace,
  del,
  moveVertical,
  lineStart,
  lineEnd,
  selBounds,
  hasSelection,
  typeText,
  backspaceSel,
  deleteSel,
  emptyHistory,
  recordEdit,
  breakRun,
  undo,
  redo,
  HISTORY_LIMIT,
  type Measure,
  type DLine,
  type EditState,
  type SelEdit,
  type EditKind,
  type History,
} from "@pocketjs/framework/text-edit";
